name: UI Automation Stag & Preview

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Test environment"
        required: true
        default: "stag"
        type: choice
        options:
          - stag
          - prod
          - dev

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install WireGuard and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools resolvconf iptables dnsutils curl

      - name: Setup WireGuard VPN
        env:
          WG_PRIVATE_KEY: ${{ secrets.WG_PRIVATE_KEY }}
          WG_PRESHARED_KEY: ${{ secrets.WG_PRESHARED_KEY }}
        run: |
          echo "=== Setting up WireGuard VPN ==="

          # Create WireGuard configuration with optimized settings
          sudo tee /etc/wireguard/wg0.conf > /dev/null <<EOF
          [Interface]
          PrivateKey = ${WG_PRIVATE_KEY}
          Address = 10.0.0.10/24
          DNS = 1.1.1.1, 8.8.8.8
          MTU = 1420

          [Peer]
          PublicKey = DdlxB8CIQ72tZ6bWe3NU/ZC50SKIqKgmiHusPM4liAI=
          PresharedKey = ${WG_PRESHARED_KEY}
          AllowedIPs = 0.0.0.0/0, ::/0
          PersistentKeepalive = 25
          Endpoint = vpn.juliusworks.com:33048
          EOF

          # Set proper permissions
          sudo chmod 600 /etc/wireguard/wg0.conf

          # Enable IP forwarding
          echo 'net.ipv4.ip_forward = 1' | sudo tee -a /etc/sysctl.conf
          echo 'net.ipv6.conf.all.forwarding = 1' | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p

          echo "=== Starting WireGuard interface ==="
          # Start WireGuard interface
          sudo wg-quick up wg0

          # Wait for interface to be fully up
          sleep 10

          echo "=== Testing target application connectivity ==="
          for i in {1..5}; do
            echo "Attempt $i: Testing app connectivity..."
            if curl -I --connect-timeout 10 --max-time 20 https://app.juliusdev.net/login; then
              echo "✓ Application connectivity successful"
              break
            else
              echo "✗ Application connectivity failed, retrying..."
              sleep 10
            fi
          done

          # Final verification
          curl -v --connect-timeout 15 --max-time 30 https://app.juliusdev.net/login || {
            echo "❌ CRITICAL: Cannot reach target application"
            exit 1
          }

          echo "✅ VPN setup completed successfully"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers with system dependencies
        run: |
          # Install browsers with all system dependencies
          npx playwright install --with-deps chromium

          # Verify browser installation
          npx playwright --version

      - name: Configure system for browser stability
        run: |
          # Increase shared memory for browser stability
          sudo mount -o remount,size=2G /dev/shm

          # Set memory limits
          echo "Setting up memory management..."
          sudo sysctl -w vm.swappiness=10
          sudo sysctl -w vm.overcommit_memory=1

          # Show available resources
          echo "=== System Resources ==="
          free -h
          df -h

      - name: Create optimized Playwright config for CI
        run: |
          # Create a CI-specific config file using Playwright's default directories
          cat > playwright.ci.config.js << 'EOF'
          const { defineConfig, devices } = require('@playwright/test');

          module.exports = defineConfig({
            testDir: './playwright-automation-framework/src/tests',
            fullyParallel: false,
            forbidOnly: !!process.env.CI,
            retries: 2,
            workers: 1, // Single worker to avoid resource conflicts
            reporter: [
              ['list'], 
              ['html', { open: 'never' }]  // Uses default 'playwright-report' directory
            ],
            // Use default 'test-results' directory for test artifacts
            timeout: 120000, // 2 minutes per test
            expect: {
              timeout: 20000 // 20 seconds for assertions
            },
            use: {
              baseURL: 'https://app.juliusdev.net',
              trace: 'retain-on-failure',
              video: 'retain-on-failure',
              screenshot: 'only-on-failure',
              navigationTimeout: 60000, // 60 seconds for navigation
              actionTimeout: 30000, // 30 seconds for actions
            },
            projects: [
              {
                name: 'chromium',
                use: {
                  ...devices['Desktop Chrome'],
                  launchOptions: {
                    // Optimized browser flags for CI
                    args: [
                      '--no-sandbox',
                      '--disable-setuid-sandbox',
                      '--disable-dev-shm-usage',
                      '--disable-web-security',
                      '--disable-features=VizDisplayCompositor',
                      '--disable-gpu',
                      '--disable-background-timer-throttling',
                      '--disable-backgrounding-occluded-windows',
                      '--disable-renderer-backgrounding',
                      '--disable-field-trial-config',
                      '--disable-ipc-flooding-protection',
                      '--memory-pressure-off',
                      '--max_old_space_size=4096'
                    ],
                    // Ensure browser doesn't timeout
                    timeout: 60000,
                  },
                  // Use a larger viewport for stability
                  viewport: { width: 1280, height: 720 },
                }
              }
            ]
          });
          EOF

      - name: Final pre-test connectivity check
        run: |
          echo "=== Final connectivity verification before tests ==="
          curl -I --connect-timeout 15 --max-time 30 https://app.juliusdev.net/login || {
            echo "❌ FINAL CHECK FAILED: Cannot reach application"
            exit 1
          }
          echo "✅ All connectivity checks passed"

      - name: Run Playwright tests with stability optimizations
        env:
          TEST_ENV: ${{ github.event.inputs.environment }}
          NODE_OPTIONS: "--max-old-space-size=4096"
          PWDEBUG: 0
        run: |
          echo "Running tests against $TEST_ENV environment with CI optimizations"

          # Set process limits
          ulimit -n 8192

          # Run tests with the CI config
          npx playwright test --config=playwright.ci.config.js \
            --reporter=list \
            --max-failures=1 \
            --timeout=120000
        continue-on-error: false

      - name: Check test result directories
        if: always()
        run: |
          echo "=== Checking for test result directories ==="
          pwd
          ls -la
          echo "--- Looking for playwright-report ---"
          ls -la playwright-report/ || echo "playwright-report directory not found"
          echo "--- Looking for test-results ---"  
          ls -la test-results/ || echo "test-results directory not found"
          echo "--- Looking for any result directories ---"
          find . -name "*result*" -o -name "*report*" | head -10

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results-${{ github.event.inputs.environment }}
          path: |
            playwright-report/
            test-results/
          retention-days: 7

      - name: Debug info on failure
        if: failure()
        run: |
          echo "=== Debug info for failed run ==="
          # System resources
          free -h
          df -h /dev/shm

          # Process info
          ps aux | grep chrome || echo "No chrome processes found"

          # VPN status
          sudo wg show

      - name: Cleanup WireGuard
        if: always()
        run: |
          echo "Cleaning up WireGuard connection..."
          sudo wg-quick down wg0 || echo "WireGuard interface already down"
