name: Playwright Tests with VPN

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      environment:
        description: "Test environment"
        required: false
        default: "stag" # Changed to lowercase to match your environment
        type: choice
        options:
          - stag
          #- preview
          #- production
      browser:
        description: "Browser to test"
        required: false
        default: "chromium"
        type: choice
        options:
          - chromium
          #- Firefox
          #- Webkit
          #- Edge

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'stag' }} # This is crucial for environment secrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard

      - name: Configure WireGuard VPN
        run: |
          # Create config file line by line to avoid interpolation issues
          sudo mkdir -p /etc/wireguard
          echo "[Interface]" | sudo tee /etc/wireguard/wg0.conf
          echo "PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}" | sudo tee -a /etc/wireguard/wg0.conf
          echo "Address = 10.0.0.10/24" | sudo tee -a /etc/wireguard/wg0.conf
          echo "DNS = 1.1.1.1" | sudo tee -a /etc/wireguard/wg0.conf
          echo "" | sudo tee -a /etc/wireguard/wg0.conf
          echo "[Peer]" | sudo tee -a /etc/wireguard/wg0.conf
          echo "PublicKey = ${{ secrets.WG_PUBLIC_KEY }}" | sudo tee -a /etc/wireguard/wg0.conf
          echo "PresharedKey = ${{ secrets.WG_PRESHARED_KEY }}" | sudo tee -a /etc/wireguard/wg0.conf
          echo "AllowedIPs = 0.0.0.0/0, ::/0" | sudo tee -a /etc/wireguard/wg0.conf
          echo "Endpoint = ${{ secrets.WG_ENDPOINT }}" | sudo tee -a /etc/wireguard/wg0.conf
          echo "PersistentKeepalive = 25" | sudo tee -a /etc/wireguard/wg0.conf

          # Set proper permissions
          sudo chmod 600 /etc/wireguard/wg0.conf

          # Debug: Check if config file is created properly
          echo "Config file content:"
          sudo cat /etc/wireguard/wg0.conf

          # Bring up the VPN
          sudo wg-quick up wg0
          sleep 10
          echo "✅ VPN connected"

      - name: Test VPN Connection
        run: |
          echo "WireGuard Status:"
          sudo wg show
          echo ""
          echo "Public IP (via VPN):"
          curl -s ifconfig.me
          echo ""
          echo "Pinging Google DNS:"
          ping -c 4 8.8.8.8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: |
          # Try npm ci first, fallback to npm install if sync issues occur
          npm ci || (echo "Lock file out of sync, running npm install..." && npm install)

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          if [ "${{ github.event.inputs.browser }}" = "all" ]; then
            npx playwright test
          else
            npx playwright test --project=${{ github.event.inputs.browser }}
          fi
        env:
          CI: true
          TEST_ENV: ${{ github.event.inputs.environment }}

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ github.event.inputs.browser || 'chromium' }}-${{ github.run_number }}
          path: result/playwright-report/
          retention-days: 30

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.event.inputs.browser || 'chromium' }}-${{ github.run_number }}
          path: result/test-results/
          retention-days: 30

      - name: Test Results Summary
        if: always()
        run: |
          echo "## 🎭 Playwright Test Execution Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ github.event.inputs.environment || 'stag' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Browser**: ${{ github.event.inputs.browser || 'chromium' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Run Number**: ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Timestamp**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- **VPN**: ✅ Connected via WireGuard" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📊 **Reports**: Download artifacts from this workflow run" >> $GITHUB_STEP_SUMMARY

      - name: Cleanup VPN Connection
        if: always()
        run: |
          sudo wg-quick down wg0 || echo "VPN already disconnected"
          sudo rm -f /etc/wireguard/wg0.conf
          echo "🔒 VPN connection cleaned up"
